import React from 'react';
import { useParams, Link } from 'react-router-dom';
import { Card, CardHeader, CardTitle, CardContent, CardDescription } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Download } from 'lucide-react';

// Demo data (should be replaced with real data or fetched from backend)
const departmentReports = [
  // ...same demo data as in AdminDashboard, or fetch from backend...
  {
    id: 9,
    name: 'ICT Lab Device Inventory - July 2025',
    type: 'Inventory',
    generatedBy: 'ICT Admin',
    date: '2025-07-01',
    format: 'PDF',
    size: '2.0 MB',
    department: 'ict_lab',
  },
  {
    id: 10,
    name: 'Software Usage Stats - Q2 2025',
    type: 'Usage',
    generatedBy: 'ICT Analyst',
    date: '2025-06-30',
    format: 'Excel',
    size: '1.2 MB',
    department: 'ict_lab',
  },
];

const DepartmentReportPage: React.FC = () => {
  const { department } = useParams();
  const reports = departmentReports.filter(r => r.department === department);

  return (
    <div className="min-h-screen flex flex-col items-center justify-center bg-gradient-to-br from-blue-50 via-white to-blue-100 p-6">
      <Card className="w-full max-w-3xl shadow-2xl border-0 bg-white/90 rounded-2xl">
        <CardHeader className="pb-2">
          <CardTitle style={{ fontFamily: 'Ubuntu, sans-serif', fontWeight: 700, fontSize: '2.5rem', color: '#1a237e', letterSpacing: '0.03em' }}>
            {department?.replace('_', ' ').toUpperCase()} Reports
          </CardTitle>
          <CardDescription style={{ fontFamily: 'Ubuntu, sans-serif', fontWeight: 500, color: '#3949ab', fontSize: '1.15rem' }}>
            All reports for this department
          </CardDescription>
        </CardHeader>
        <CardContent>
          {reports.length === 0 ? (
            <div className="text-center text-muted-foreground py-8">No reports found for this department.</div>
          ) : (
            <div className="overflow-x-auto rounded-lg border border-blue-200 bg-white shadow-lg">
              <table className="min-w-full text-sm">
                <thead>
                  <tr className="bg-blue-100" style={{ fontFamily: 'Ubuntu, sans-serif', fontWeight: 600, fontSize: '1.1rem', color: '#1a237e' }}>
                    <th className="p-4 text-left">Report Name</th>
                    <th className="p-4 text-left">Type</th>
                    <th className="p-4 text-left">Generated By</th>
                    <th className="p-4 text-left">Date</th>
                    <th className="p-4 text-left">Format</th>
                    <th className="p-4 text-left">Size</th>
                    <th className="p-4 text-left">Action</th>
                  </tr>
                </thead>
                <tbody>
                  {reports.map((report) => (
                    <tr key={report.id} className="border-b hover:bg-blue-50 transition-all">
                      <td className="p-4" style={{ fontFamily: 'Ubuntu, sans-serif', fontWeight: 500 }}>{report.name}</td>
                      <td className="p-4"><Badge variant="outline" className="px-2 py-1 text-xs font-medium bg-blue-100 text-blue-700 border-0">{report.type}</Badge></td>
                      <td className="p-4">{report.generatedBy}</td>
                      <td className="p-4">{report.date}</td>
                      <td className="p-4">{report.format}</td>
                      <td className="p-4">{report.size}</td>
                      <td className="p-4">
                        <Button size="sm" variant="outline" style={{ fontFamily: 'Ubuntu, sans-serif', fontWeight: 500 }} className="rounded-full px-4 py-2 shadow hover:bg-blue-100">
                          <Download className="w-4 h-4 mr-1 text-blue-700" /> Download
                        </Button>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
          <div className="mt-8 text-center">
            <Link to="/" className="text-blue-700 underline font-medium">Back to Dashboard</Link>
          </div>
        </CardContent>
      </Card>
    </div>
  );
};

export default DepartmentReportPage;
