import React from 'react';
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Download, Store, ArrowRight } from 'lucide-react';
import { useStores } from '@/hooks/useStores';
import { useNavigate, useParams, Routes, Route } from 'react-router-dom';

// Simulated reports per department
const departmentReports = [
  {
    id: 1,
    name: 'Monthly Inventory Report - January 2024',
    type: 'Inventory',
    generatedBy: 'Admin',
    date: '2024-01-16',
    format: 'PDF',
    size: '2.4 MB',
    department: 'library',
  },
  {
    id: 2,
    name: 'User Activity Summary - Q4 2023',
    type: 'User Activity',
    generatedBy: 'System',
    date: '2024-01-01',
    format: 'Excel',
    size: '1.8 MB',
    department: 'laboratory',
  },
  {
    id: 3,
    name: 'Financial Report - December 2023',
    type: 'Financial',
    generatedBy: 'Bursar',
    date: '2023-12-31',
    format: 'PDF',
    size: '3.2 MB',
    department: 'kitchen',
  },
  {
    id: 4,
    name: 'Sports Store Usage - March 2024',
    type: 'Usage',
    generatedBy: 'Admin',
    date: '2024-03-10',
    format: 'PDF',
    size: '1.1 MB',
    department: 'sports',
  },
  {
    id: 5,
    name: 'ICT Lab Equipment Report - April 2024',
    type: 'Inventory',
    generatedBy: 'ICT Admin',
    date: '2024-04-05',
    format: 'Excel',
    size: '2.0 MB',
    department: 'ict_lab',
  },
];



export function DepartmentDropdownNav({ stores }: { stores: any[] }) {
  const navigate = useNavigate();
  const [selected, setSelected] = React.useState('');
  React.useEffect(() => {
    if (selected) {
      navigate(`/stores/${selected}`);
    }
  }, [selected, navigate]);
  return (
    <div className="max-w-xs">
      <label className="block mb-2 font-medium">Department</label>
      <select
        className="w-full border rounded px-3 py-2"
        value={selected}
        onChange={e => setSelected(e.target.value)}
      >
        <option value="">Select department...</option>
        {stores.map((store: any) => (
          <option key={store.id} value={store.store_type}>
            {store.name} ({store.store_type.replace('_', ' ')})
          </option>
        ))}
      </select>
    </div>
  );
}

// Department reports page
const DepartmentReports: React.FC = () => {
  const { department } = useParams();
  const navigate = useNavigate();
  const { stores } = useStores();
  const store = stores.find((s: any) => s.store_type === department);

  const handleDownloadReport = (report: any) => {
    let content = '';
    let mimeType = '';
    let fileExtension = '';
    if (report.format.toLowerCase() === 'pdf') {
      content = `PDF Report: ${report.name}\nType: ${report.type}\nGenerated by: ${report.generatedBy}\nDate: ${report.date}`;
      mimeType = 'application/pdf';
      fileExtension = 'pdf';
    } else if (report.format.toLowerCase() === 'excel') {
      content = `Excel Report: ${report.name}\nType: ${report.type}\nGenerated by: ${report.generatedBy}\nDate: ${report.date}`;
      mimeType = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';
      fileExtension = 'xlsx';
    } else {
      content = `Report: ${report.name}`;
      mimeType = 'text/plain';
      fileExtension = 'txt';
    }
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${report.name.replace(/\s+/g, '_')}.${fileExtension}`;
    document.body.appendChild(a);
    a.click();
    setTimeout(() => {
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    }, 100);
  };

  if (!store) {
    return <div className="p-6">Department not found.</div>;
  }

  return (
    <div className="space-y-6">
      <Button variant="outline" onClick={() => navigate('/stores')} className="mb-4">&larr; Back to Departments</Button>
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Store className="w-5 h-5" />
            {store.name} Reports
          </CardTitle>
          <CardDescription>
            All reports for {store.name} ({store.store_type.replace('_', ' ')})
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className="overflow-x-auto">
            <table className="min-w-full text-sm border">
              <thead>
                <tr className="bg-muted">
                  <th className="p-2 text-left">Report Name</th>
                  <th className="p-2 text-left">Type</th>
                  <th className="p-2 text-left">Generated By</th>
                  <th className="p-2 text-left">Date</th>
                  <th className="p-2 text-left">Format</th>
                  <th className="p-2 text-left">Size</th>
                  <th className="p-2 text-left">Action</th>
                </tr>
              </thead>
              <tbody>
                {departmentReports.filter(r => r.department === department).length === 0 ? (
                  <tr><td colSpan={7} className="p-4 text-center text-muted-foreground">No reports found for this department.</td></tr>
                ) : (
                  departmentReports.filter(r => r.department === department).map((report) => (
                    <tr key={report.id} className="border-b">
                      <td className="p-2">{report.name}</td>
                      <td className="p-2">{report.type}</td>
                      <td className="p-2">{report.generatedBy}</td>
                      <td className="p-2">{report.date}</td>
                      <td className="p-2">{report.format}</td>
                      <td className="p-2">{report.size}</td>
                      <td className="p-2">
                        <Button size="sm" variant="outline" onClick={() => handleDownloadReport(report)}>
                          <Download className="w-4 h-4 mr-1" /> Download
                        </Button>
                      </td>
                    </tr>
                  ))
                )}
              </tbody>
            </table>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}

const StoresPage: React.FC = () => {
  const { stores } = useStores();
  return (
    <Routes>
      <Route
        path="/"
        element={
          <div className="space-y-6">
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Store className="w-5 h-5" />
                  Department Reports
                </CardTitle>
                <CardDescription>
                  Select a department from the dropdown to view and download its reports
                </CardDescription>
              </CardHeader>
              <CardContent>
                <DepartmentDropdownNav stores={stores} />
              </CardContent>
            </Card>
          </div>
        }
      />
      <Route path=":department" element={<DepartmentReports />} />
    </Routes>
  );
};

export default StoresPage;
